### ISSUE TITLE
Auth API not working

### ISSUE THREAD

**Issue by davidvexel** [samarthagarwal/wooionic#6]
Hey there, what auth plugin are you using in your site? I tried using json-api and json-api-auth but it doesn't work, I just get this message when trying to get the auth cookie.

```json
{
"status": "error",
"error": "Unknown controller 'auth'."
}
```

**Comment by davidvexel** [comment]
my endpoint looks like this
```
http://local.dev/api/auth/generate_auth_cookie/?nonce=375034fjwfn39u8&user_id=admin&password=pass
```

**Comment by samarthagarwal** [comment]
Hi. Make sure you have enabled the AUTH from the JSON API settings page.

**Comment by davidvexel** [comment]
Yeah, that made it. Thank you very much.

**Comment by m-oudah** [comment]
> Hi. Make sure you have enabled the AUTH from the JSON API settings page.

thanks that helped me
